- name: Deply Kubernetes resources to Minikube
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Start Minikbe if it's not running
      command: minikube start --driver=docker --force

    - name: Wait for Minikube to be ready
      command: minikube status

    - name: Applying the ConfigMap
      command: kubectl apply -f db_config.yaml
  
    - name: Apply Kubernetes Deployment
      command: kubectl apply -f forum_deployment.yaml  

    - name: Apply Kubernetes Service
      command: kubectl apply -f forum_service.yaml
